spring.application.name=GlicoGuard
server.port=8080
spring.thymeleaf.cache=false
server.servlet.session.timeout=15m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GLICOGUARD_MAIL_USERNAME:aula7b2026@gmail.com}
spring.mail.password=${GLICOGUARD_MAIL_PASSWORD:umetkklzbblyopsf}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
glicoguard.security.require-https=false
glicoguard.security.pbkdf2.iterations=120000
glicoguard.security.pbkdf2.key-length=256
glicoguard.security.login.max-attempts=5
glicoguard.security.login.lock-minutes=15
glicoguard.security.two-factor.expiration-minutes=5
glicoguard.security.reset.expiration-minutes=10
glicoguard.security.consent.version=2026.1
glicoguard.security.consent.purpose=Tratamento de dados de autenticacao, saude e seguranca para operacao do GlicoGuard
glicoguard.mail.enabled=${GLICOGUARD_MAIL_ENABLED:true}
glicoguard.mail.from=${GLICOGUARD_MAIL_USERNAME:aula7b2026@gmail.com}
glicoguard.mail.require-real-delivery=${GLICOGUARD_MAIL_REQUIRE_REAL_DELIVERY:true}
